# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false # By default, Vagrant will try and change the insecure SSH key to a better one. This won't work for us as it does not know how to talk VyOS.
  config.vm.box = "vyos-1.3.0-rc6.box" # Use the vyos box image
  config.vm.synced_folder '.', '/vagrant', disabled: true # Disable shared folders
  config.vm.guest = :linux # Tell Vagrant that it is Linux so it doesn't error

  config.vm.define "vyos1" do |vyos1| # On vyos1, configure 2 additional NICs
    vyos1.vm.network 'private_network', auto_config: false, nic_type: 'virtio', virtualbox__intnet: "vyos1_vyos2"
    vyos1.vm.network 'private_network', auto_config: false, nic_type: 'virtio', virtualbox__intnet: "vyos1_internal"
  end

  config.vm.define "vyos2" do |vyos2| # On vyos2, configure 2 additional NICs
    vyos2.vm.network 'private_network', auto_config: false, nic_type: 'virtio', virtualbox__intnet: "vyos1_vyos2"
    vyos2.vm.network 'private_network', auto_config: false, nic_type: 'virtio', virtualbox__intnet: "vyos2_internal"
  end
end